#!/usr/bin/env node
/**
 * Bundle the VINTAGE mark for the app.
 *
 * The iOS app shows the turning V inside a transparent web view. That view
 * loads one self-contained page — three.js, the mark, the scene — as a
 * string carried in the JS bundle, so the front door needs no network and
 * fetches nothing. This script builds that page from public/3d/app.js with
 * esbuild and writes it to src/brand/markHtml.generated.ts.
 *
 * Run it after changing public/3d/app.js, mark.js or the vendored three.js:
 *
 *   npm run build:mark
 *
 * The output is committed, so a checkout builds without running this.
 */
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));

const result = await build({
  entryPoints: [`${root}public/3d/app.js`],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["safari15"],
  write: false,
  legalComments: "none",
  logLevel: "warning",
});
const js = result.outputFiles[0].text;

// The body's data-fill is filled in by the app per use (MarkStage), which is
// the one place this string is changed before it is shown.
const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<style>html,body{margin:0;height:100%;background:transparent;overflow:hidden}canvas{display:block}</style>
</head><body data-fill="__FILL__"><script>${js}</script></body></html>`;

mkdirSync(`${root}src/brand`, { recursive: true });
writeFileSync(
  `${root}src/brand/markHtml.generated.ts`,
  `// Generated by scripts/build-mark.mjs from public/3d/app.js — do not edit; run \`npm run build:mark\`.\n` +
    `// The VINTAGE mark's scene as one self-contained page for the app's web view (three.js r184 inside).\n` +
    `/* eslint-disable */\n` +
    `export const MARK_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`mark: ${(js.length / 1024).toFixed(0)} KB of script → src/brand/markHtml.generated.ts`);
